# Numpy
**NumPy stands for Numerical Python.**

**NumPy is a Python library used for working with arrays.**

**It also has functions for working in domain of linear algebra, fourier transform, and matrices.**

**NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.**

**The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.**

In [2]:
import numpy as np

In [3]:
#1-d Array
arr1=np.array([1,2,3,4])

In [4]:
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
print(arr1.ndim)

1


In [7]:
#2-d Array
arr2=np.array([[1,2,3],[4,5,6]])

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(arr2.ndim)

2


In [10]:
arr3=np.zeros((2,4))

In [11]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
print(arr3.ndim)

2


In [13]:
type(arr3)

numpy.ndarray

In [14]:
arr4=np.ones((3,3))

In [15]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# 0-d Array
arr=np.array(55)
arr

array(55)

In [94]:
# Accessing Array Elements
arr1=np.array([1,2,3,4,5])
arr1


array([1, 2, 3, 4, 5])

In [96]:
print(arr1[0])

1


In [18]:
arr1[3]

4

In [19]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#2nd element on 1st row
arr2[0]

array([1, 2, 3])

In [21]:
arr2[1]

array([4, 5, 6])

In [22]:
arr2[1,1]

5

In [23]:
import numpy as np

arr3 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr3[1:5])

[2 3 4 5]


In [24]:
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1[:5])

[1 2 3 4 5]


In [25]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[4:])

[5 6 7]


In [26]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr5[:4])

[1 2 3 4]


In [27]:
arr6 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr6[-3:-1])

[5 6]


In [28]:
#Return every other element from index 1 to index 5:

arr7 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr7[1:5:2])

[2 4]


In [29]:
arr=np.array([56,34,3,2,23,1,2,3,4,5,342,3423])
print(arr.reshape(2,3,2))

[[[  56   34]
  [   3    2]
  [  23    1]]

 [[   2    3]
  [   4    5]
  [ 342 3423]]]


In [30]:
# Shape of an Array: shape that returns a tuple with each index having the number of corresponding elements.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [31]:
#Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
# Iterating Arrays
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [34]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [35]:
arr=np.array([1,2,3,4,5])
arr1=np.array([23,34,21,45])
arr3=np.concatenate((arr,arr1))
print(arr3)

[ 1  2  3  4  5 23 34 21 45]


In [36]:
# NumPy Joining Array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5,234,24,3545,6], [7,23,434,2,8]])

arr=np.concatenate((arr1,arr2),axis=1)

print(arr)

[[   1    2    5  234   24 3545    6]
 [   3    4    7   23  434    2    8]]


In [39]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2,3], [3,34, 4]])

arr2 = np.array([[5,36,64,87], [7,90,77,8]])

arr = np.concatenate((arr2, arr1), axis=1)

print(arr)

[[ 5 36 64 87  1  2  3]
 [ 7 90 77  8  3 34  4]]


In [40]:
#Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr=np.array_split(arr,2)

print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [42]:
# Random Numbers
# NumPy offers the random module to work with random numbers.
# Generate a random integer from 0 to 100:
from numpy import random

x = random.randint(10)

print(x)

0


In [43]:
# Random module's rand() method returns a random float between 0 and 1.
from numpy import random

x = random.rand(5)

print(x)

[0.58639621 0.90526106 0.89752709 0.86621271 0.87263609]


In [44]:
# Generate Random Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[16 38 60 90 90]


In [45]:
# A 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[13 47 85 15 32]
 [69 49 33 70 40]
 [32 77 68 74 91]]


In [46]:
# Generate a 1-D array containing 5 random floats:
from numpy import random

x = random.rand(5)

print(x)

[0.79955018 0.78541034 0.26757084 0.81509841 0.15517443]


In [47]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random

x = random.randint(2,10)

print(x)

2
